### ISSUE TITLE
Chapter IV - Mission 01: Missing Step

### ISSUE THREAD

**Issue by schmidtsabine** [TYPO3GmbH/mainzific_rim#2]
I tried to set a new password for the user Bob Bernsteiner. 

In the Mainzific Rim Setup, Bob Bernsteiner ist categorized as Backend User and not as a Trusted News Reporter with a Frontend Login like D. Strangelove, E. Brown and J. Whittaker. 
I can only change his Backend Password (which should not be able for me as editor), not a frontend password.

Missing Step: Frondend User Entry for Bob Bernsteiner.

**Comment by Weissheiten** [comment]
thank you for reporting this, we'll look into the topic
