### ISSUE TITLE
Update the README for V9

### ISSUE THREAD

**Issue by oliverklee** [TYPO3GmbH/mainzific_rim#3]
As an integrator setting up the site, I'd like to have the information in the README to be correct because I do not want to be confused.

## Acceptance criteria
The TYPO3 version mentioned in the README should match the versions used in the `composer.json`, i.e., refer to TYPO3 9.5.

**Comment by susannemoog** [comment]
Readme was updated by the PR - Description of this Repository was also updated --> closing here :)

**Comment by oliverklee** [comment]
Thanks!
